### ISSUE TITLE
Ingest fine, output doesn't work?

### ISSUE THREAD

**Issue by stwr** [ravenium/srt-live-server#3]
Hi,

Apologies if this is considered more of a support question than an issue. I'll let you decide;

My setup is as follows;

SRT-live-server docker: 192.168.1.198:1935
Transmitting MacBook running OBS: 192.168.1.100
Receiving Linux server running OBS and VLC: 192.168.1.101 
2nd Receiving MacBook running OBS and VLC for troubleshooting: 192.168.1.102

I'm trying to send an SRT stream from the MacBook to the SRT server and then pick it up using the Linux Server in OBS.

It appears I can stream into the SRT Docker with no problem. I've put in the stream details in OBS as: srt://192.168.1.198:1935?streamid=input/live/stream1

This starts correctly with no issues. Green light in OBS.

When trying picking up the stream on VLC or OBS I use the following string:
srt://192.168.1.198:1935?streamid=output/live/stream1

And would expect this to work. however, neither VLC nor OBS will load the stream. No errors are thrown.

Is this an issue that has been seen before?

Thanks,

stwr

**Comment by ravenium** [comment]
Hrm...the stream URL looks correct.  I do know that VLC doesn't support streamid (yet) without a patch as this was relatively recent (~December of last year).  As far as OBS, I do know I've had trouble with multi-receive at times - is it possive you're hooking the same stream twice?  I'm sure that's supposed to eventually work (like RTMP) but I definitely ran into issues.

Also, run docker attached and check what the console output says.  It'll be a lot of debug spaghetti but it should show when you try to connect and what the associated failures are.  That way you can track down if it's a networking thing or an SRT thing.

**Comment by unusualcrow** [comment]
I'm having the same issue, no idea why.

**Comment by unusualcrow** [comment]
Nevermind, it seems to work fine now?... Was having the same issue and after restarting a couple times with no changes it worked with no issue

**Comment by ravenium** [comment]
Pushed a small update to make it work with docker-compose the other day - when in doubt, you can tweak your config and see how it looks.  Closing this for now but definitely re-open if you spot anything (and c/p console logs if you can).

**Comment by gregfr** [comment]
I have the same problem: ingress looks fine:

```
2021-03-17 09:58:18:536 SLS INFO: [0x7f51e6b1ae88]CSLSMapData::add ok, key='input/live/yourstreamname'.
2021-03-17 09:58:18:536 SLS INFO: [0x559f4d0e7d48]CSLSMapPublisher::set_push_2_pushlisher, ok, publisher=0x559f4ec0c5c0, app_streamname=input/live/yourstreamname, m_map_push_2_pushlisher.size()=1.
2021-03-17 09:58:18:536 SLS INFO: [0x559f4ebc1520]CSLSListener::handler, new publisher[172.17.0.1:34719], key_stream_name=input/live/yourstreamname.
2021-03-17 09:58:18:536 SLS INFO: [0x559f4d0e7e48]CSLSMapRelay::add_relay_manager, no relay conf info, app_uplive=input/live, stream_name=yourstreamname.
2021-03-17 09:58:18:536 SLS INFO: [0x559f4ebc1520]CSLSListener::handler, m_map_pusher->add_relay_manager failed, new role[172.17.0.1:34719], key_stream_name=input/live/yourstreamname.
```

However I cannot play it. VLC and MPlayer give an error, as ffplay:

`ffplay "srt://localhost:1935?streamid=ouput/live/yourstreamname"`

```
[srt @ 0x7f8394001740] Connection was broken  
srt://localhost:1935?streamid=ouput/live/yourstreamname: Unknown error occurred
```

I will try to recompile a newest version of ffmpeg, the one I'm using is from July 2020.

**Comment by ravenium** [comment]
Just a heads up, I've sort of laid this to rest a bit as me debugging C++ is a terrible idea (ha) and It looks like the author of srt-live-server has gone a bit quiet as well.  I can swear up and down the docker invocation should work, but that probably doesn't  help you :)

If you've got the appetite for something that was written in the spirit of SLS and is being actively maintained (and in Go, which I understand a bit better, no less!) check out [https://github.com/voc/srtrelay](url).  I dockerized it a bit and added a cheesy frontend that restreams to HLS here: [https://github.com/ravenium/fragconsole](url).  Going forward, it's probably a better shot to be maintained.
