### ISSUE TITLE
Failed to build using Dockerfile

### ISSUE THREAD

**Issue by DigibitDK** [ravenium/srt-live-server#9]
Can't seem to build the image using the provided dockerfile.
Ubuntu 22.04 LTS

![2023-05-04 01_33_41-root@DigibitDS01_ ~_srt_rav](https://user-images.githubusercontent.com/69547207/236073357-f4aa7f28-ddf9-4b7e-bbc7-cd79cf5dc6db.png)

**Comment by ravenium** [comment]
I'm not the best with C++ these days, but it looks like there's an issue with ctime on alpine these days.  I made a kludgey bash hack that should allow it to compile.

FWIW the original project seems to have been largely abandoned 3 years ago. For updated SRT relay, I'd recommend https://github.com/voc/srtrelay as it's written in Golang (easier to understand IMO) and works better with newer SRT library versions.
